# Generated by Django 5.1.2 on 2024-11-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=244)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mehmonxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=244)),
                ('yulduzlar_soni', models.IntegerField()),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muddati', models.DateTimeField(auto_created=True)),
                ('nomi', models.CharField(max_length=244)),
                ('izoh', models.CharField(max_length=244)),
                ('narxi', models.IntegerField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.klass')),
                ('mehmonxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.mehmonxona')),
            ],
        ),
    ]
